// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod foxglove {


pub enum TimeOffset {}
#[derive(Copy, Clone, PartialEq)]

/// A time value
pub struct Time<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Time<'a> {
  type Inner = Time<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Time<'a> {
  pub const VT_SEC: ::flatbuffers::VOffsetT = 4;
  pub const VT_NSEC: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Time { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TimeArgs
  ) -> ::flatbuffers::WIPOffset<Time<'bldr>> {
    let mut builder = TimeBuilder::new(_fbb);
    builder.add_nsec(args.nsec);
    builder.add_sec(args.sec);
    builder.finish()
  }


  /// Seconds since epoch
  #[inline]
  pub fn sec(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Time::VT_SEC, Some(0)).unwrap()}
  }
  /// Nanoseconds since the last second
  #[inline]
  pub fn nsec(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Time::VT_NSEC, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Time<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("sec", Self::VT_SEC, false)?
     .visit_field::<u32>("nsec", Self::VT_NSEC, false)?
     .finish();
    Ok(())
  }
}
pub struct TimeArgs {
    pub sec: u32,
    pub nsec: u32,
}
impl<'a> Default for TimeArgs {
  #[inline]
  fn default() -> Self {
    TimeArgs {
      sec: 0,
      nsec: 0,
    }
  }
}

pub struct TimeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TimeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_sec(&mut self, sec: u32) {
    self.fbb_.push_slot::<u32>(Time::VT_SEC, sec, 0);
  }
  #[inline]
  pub fn add_nsec(&mut self, nsec: u32) {
    self.fbb_.push_slot::<u32>(Time::VT_NSEC, nsec, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TimeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TimeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Time<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Time<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Time");
      ds.field("sec", &self.sec());
      ds.field("nsec", &self.nsec());
      ds.finish()
  }
}
}  // pub mod foxglove

