// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

use crate::infra::foxglove::time_generated::foxglove::*;

#[allow(unused_imports, dead_code)]
pub mod foxglove {

  use crate::infra::foxglove::time_generated::foxglove::*;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_LOG_LEVEL: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_LOG_LEVEL: u8 = 5;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_LOG_LEVEL: [LogLevel; 6] = [
  LogLevel::UNKNOWN,
  LogLevel::DEBUG,
  LogLevel::INFO,
  LogLevel::WARNING,
  LogLevel::ERROR,
  LogLevel::FATAL,
];

/// Log level
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct LogLevel(pub u8);
#[allow(non_upper_case_globals)]
impl LogLevel {
  /// Unknown log level
  pub const UNKNOWN: Self = Self(0);
  /// Debug log level
  pub const DEBUG: Self = Self(1);
  /// Info log level
  pub const INFO: Self = Self(2);
  /// Warning log level
  pub const WARNING: Self = Self(3);
  /// Error log level
  pub const ERROR: Self = Self(4);
  /// Fatal log level
  pub const FATAL: Self = Self(5);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 5;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::UNKNOWN,
    Self::DEBUG,
    Self::INFO,
    Self::WARNING,
    Self::ERROR,
    Self::FATAL,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::UNKNOWN => Some("UNKNOWN"),
      Self::DEBUG => Some("DEBUG"),
      Self::INFO => Some("INFO"),
      Self::WARNING => Some("WARNING"),
      Self::ERROR => Some("ERROR"),
      Self::FATAL => Some("FATAL"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for LogLevel {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for LogLevel {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for LogLevel {
    type Output = LogLevel;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for LogLevel {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for LogLevel {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for LogLevel {}
pub enum LogOffset {}
#[derive(Copy, Clone, PartialEq)]

/// A log message
pub struct Log<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Log<'a> {
  type Inner = Log<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Log<'a> {
  pub const VT_TIMESTAMP: ::flatbuffers::VOffsetT = 4;
  pub const VT_LEVEL: ::flatbuffers::VOffsetT = 6;
  pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 8;
  pub const VT_NAME: ::flatbuffers::VOffsetT = 10;
  pub const VT_FILE: ::flatbuffers::VOffsetT = 12;
  pub const VT_LINE: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Log { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LogArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Log<'bldr>> {
    let mut builder = LogBuilder::new(_fbb);
    builder.add_line(args.line);
    if let Some(x) = args.file { builder.add_file(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    if let Some(x) = args.message { builder.add_message(x); }
    if let Some(x) = args.timestamp { builder.add_timestamp(x); }
    builder.add_level(args.level);
    builder.finish()
  }


  /// Timestamp of log message
  #[inline]
  pub fn timestamp(&self) -> Option<Time<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Time>>(Log::VT_TIMESTAMP, None)}
  }
  /// Log level
  #[inline]
  pub fn level(&self) -> LogLevel {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<LogLevel>(Log::VT_LEVEL, Some(LogLevel::UNKNOWN)).unwrap()}
  }
  /// Log message
  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Log::VT_MESSAGE, None)}
  }
  /// Process or node name
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Log::VT_NAME, None)}
  }
  /// Filename
  #[inline]
  pub fn file(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Log::VT_FILE, None)}
  }
  /// Line number in the file
  #[inline]
  pub fn line(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Log::VT_LINE, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Log<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Time>>("timestamp", Self::VT_TIMESTAMP, false)?
     .visit_field::<LogLevel>("level", Self::VT_LEVEL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("file", Self::VT_FILE, false)?
     .visit_field::<u32>("line", Self::VT_LINE, false)?
     .finish();
    Ok(())
  }
}
pub struct LogArgs<'a> {
    pub timestamp: Option<::flatbuffers::WIPOffset<Time<'a>>>,
    pub level: LogLevel,
    pub message: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub file: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub line: u32,
}
impl<'a> Default for LogArgs<'a> {
  #[inline]
  fn default() -> Self {
    LogArgs {
      timestamp: None,
      level: LogLevel::UNKNOWN,
      message: None,
      name: None,
      file: None,
      line: 0,
    }
  }
}

pub struct LogBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LogBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: ::flatbuffers::WIPOffset<Time<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Time>>(Log::VT_TIMESTAMP, timestamp);
  }
  #[inline]
  pub fn add_level(&mut self, level: LogLevel) {
    self.fbb_.push_slot::<LogLevel>(Log::VT_LEVEL, level, LogLevel::UNKNOWN);
  }
  #[inline]
  pub fn add_message(&mut self, message: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Log::VT_MESSAGE, message);
  }
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Log::VT_NAME, name);
  }
  #[inline]
  pub fn add_file(&mut self, file: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Log::VT_FILE, file);
  }
  #[inline]
  pub fn add_line(&mut self, line: u32) {
    self.fbb_.push_slot::<u32>(Log::VT_LINE, line, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> LogBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LogBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Log<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Log<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Log");
      ds.field("timestamp", &self.timestamp());
      ds.field("level", &self.level());
      ds.field("message", &self.message());
      ds.field("name", &self.name());
      ds.field("file", &self.file());
      ds.field("line", &self.line());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Log`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_log_unchecked`.
pub fn root_as_log(buf: &[u8]) -> Result<Log<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Log>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Log` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_log_unchecked`.
pub fn size_prefixed_root_as_log(buf: &[u8]) -> Result<Log<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Log>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Log` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_log_unchecked`.
pub fn root_as_log_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Log<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Log<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Log` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_log_unchecked`.
pub fn size_prefixed_root_as_log_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Log<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Log<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Log and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Log`.
pub unsafe fn root_as_log_unchecked(buf: &[u8]) -> Log<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Log>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Log and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Log`.
pub unsafe fn size_prefixed_root_as_log_unchecked(buf: &[u8]) -> Log<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Log>(buf) }
}
#[inline]
pub fn finish_log_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Log<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_log_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Log<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod foxglove

